jobs:
- job: Build_VS2019
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      x86:
        PLATFORM: 'ia32-release'
      x64:
        PLATFORM: 'x64-release'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '2.7.14' 
        addToPath: true
    - task: PowerShell@2
      inputs:
        filePath: "win-build-v8-1.ps1"
        failOnStderr: false
        ignoreLASTEXITCODE: true
        errorActionPreference: "continue"
      env:
        CONFIGURATION: $(PLATFORM)
    - task: PowerShell@2
      inputs:
        filePath: "win-build-v8-2.ps1"
      env:
        CONFIGURATION: $(PLATFORM)
    - task: PowerShell@2
      inputs:
        filePath: "win-build-v8-3.ps1"
      env:
        CONFIGURATION: $(PLATFORM)
    - task: PowerShell@2
      inputs:
        filePath: "win-build-v8-4.ps1"
      env:
        CONFIGURATION: $(PLATFORM)
    - script: nuget push *.nupkg %NUGET_API_KEY% -Source https://nuget.org/
