variables:
  V8_VERSION: '7.4.288.25'
jobs:
- job: Build_VS2019
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      x86:
        CONFIGURATION: 'ia32.release'
      x64:
        CONFIGURATION: 'x64.release'
  steps:
    - task: PowerShell@2
      displayName: "Initialize Environment"
      inputs:
        filePath: "win-build-v8-1.ps1"
    - task: PowerShell@2
      displayName: "Fetch v8 from source"
      inputs:
        filePath: "win-build-v8-2.ps1"
    - task: PowerShell@2
      displayName: "Build v8"
      inputs:
        filePath: "win-build-v8-3.ps1"
    - task: PowerShell@2
      displayName: "Create NuGet NuSpecs"
      inputs:
        filePath: "win-build-v8-4.ps1"
    - task: NuGetCommand@2
      displayName: "Create NuGet Packages"
      inputs:
        command: pack
        packagesToPack: "*.nuspec"
        versioningScheme: byEnvVar
        versionEnvVar: "V8_VERSION"
    - task: NuGetCommand@2
      displayName: "Publish NuGet Packages to NuGet Feed"
       inputs:
        command: push
        nuGetFeedType: external
        publishFeedCredentials: 'nuget.org'
        versioningScheme: byEnvVar
        versionEnvVar: "V8_VERSION"
