variables:
  V8_VERSION: '7.4.288.25'
jobs:
- job: CheckIfBuildNeeded
  displayName: "Determines if a build is necessary."
  steps:
    - task: PowerShell@2
      displayName: "Determine if a build is necessary"
      inputs:
        filePath: "checkIfBuildNeeded.ps1"
- job: Build_VS2019
  displayName: "Build v8 on Windows"
  dependsOn: CheckIfBuildNeeded
  condition: and(succeeded(), eq(variables['build_windows'], 'true'))
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      x86:
        CONFIGURATION: 'ia32.release'
      x64:
        CONFIGURATION: 'x64.release'
  steps:
    - task: NuGetToolInstaller@0
      displayName: "Ensure a recent version of NuGet"
      inputs:
        versionSpec: '4.9.x'
    - task: PowerShell@2
      displayName: "Initialize v8 build environment"
      inputs:
        filePath: "win-build-v8-1.ps1"
    - task: PowerShell@2
      displayName: "Fetch v8 from source for the specified version"
      inputs:
        filePath: "win-build-v8-2.ps1 -V8_VERSION $(V8_VERSION_WINDOWS)"
    - task: PowerShell@2
      displayName: "Build v8 according to specified configuration"
      inputs:
        filePath: "win-build-v8-3.ps1"
    - task: PowerShell@2
      displayName: "Generate NuGet .nuspec files according to specified configuration"
      inputs:
        filePath: "win-build-v8-4.ps1"
    - task: NuGetCommand@2
      displayName: "Create NuGet Packages"
      inputs:
        command: pack
        packagesToPack: "*.nuspec"
        versioningScheme: byEnvVar
        versionEnvVar: "V8_VERSION_WINDOWS"
    - task: NuGetCommand@2
      displayName: "Push NuGet Packages to NuGet Feed"
      inputs:
        command: push
        nuGetFeedType: external
        publishFeedCredentials: 'nuget.org'
        versioningScheme: byEnvVar
        versionEnvVar: "V8_VERSION_WINDOWS"
- job: Build_macOS
  displayName: "Build v8 on macOS"
  dependsOn: CheckIfBuildNeeded
  condition: and(succeeded(), eq(variables['build_macOS'], 'true'))
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix:
      x64:
        CONFIGURATION: 'x64.release'
  steps:
    - task: NuGetToolInstaller@0
      displayName: "Ensure a recent version of NuGet"
      inputs:
        versionSpec: '4.9.x'
    - task: PowerShell@2
      displayName: "Initialize v8 build environment"
      inputs:
        filePath: "macOS-build-v8-1.ps1"
    - task: PowerShell@2
      displayName: "Fetch v8 from source for the specified version"
      inputs:
        filePath: "macOS-build-v8-2.ps1 -V8_VERSION $(V8_VERSION_MACOS)"
    - task: PowerShell@2
      displayName: "Build v8 according to specified configuration"
      inputs:
        filePath: "macOS-build-v8-3.ps1"
    - task: PowerShell@2
      displayName: "Generate NuGet .nuspec files according to specified configuration"
      inputs:
        filePath: "macOS-build-v8-4.ps1"
    - task: NuGetCommand@2
      displayName: "Create NuGet Packages"
      inputs:
        command: pack
        packagesToPack: "*.nuspec"
        versioningScheme: byEnvVar
        versionEnvVar: "V8_VERSION_MACOS"
    - task: NuGetCommand@2
      displayName: "Push NuGet Packages to NuGet Feed"
      inputs:
        command: push
        nuGetFeedType: external
        publishFeedCredentials: 'nuget.org'
        versioningScheme: byEnvVar
        versionEnvVar: "V8_VERSION_MACOS"