jobs:
- job: Build_VS2019
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      x86:
        PLATFORM: 'x86'
      x64:
        PLATFORM: 'x64'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '2.7.14' 
        addToPath: true 
        architecture: 'x32'
    - script: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        where /R "%ProgramFiles(x86)%" dbghelp.dll
        where /R "%ProgramW6432%" dbghelp.dll
        python build-win.py
      env:
        CONFIGURATION: $(PLATFORM)
    - script: nuget push *.nupkg %NUGET_API_KEY% -Source https://nuget.org/
