jobs:
- job: Build_VS2019
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      x86:
        PLATFORM: 'ia32.release'
      x64:
        PLATFORM: 'x64.release'
  steps:
    - task: PowerShell@2
      displayName: "Initialize Environment"
      inputs:
        filePath: "win-build-v8-1.ps1"
      env:
        CONFIGURATION: $(PLATFORM)
    - task: PowerShell@2
      displayName: "Fetch v8 from source"
      inputs:
        filePath: "win-build-v8-2.ps1"
      env:
        CONFIGURATION: $(PLATFORM)
    - task: PowerShell@2
      displayName: "Build v8"
      inputs:
        filePath: "win-build-v8-3.ps1"
      env:
        CONFIGURATION: $(PLATFORM)
    - task: PowerShell@2
      displayName: "Create NuGet Packages"
      inputs:
        filePath: "win-build-v8-4.ps1"
      env:
        CONFIGURATION: $(PLATFORM)
    - script: nuget push *.nupkg %NUGET_API_KEY% -Source https://nuget.org/
        displayName: "Publish NuGet Packages"
