jobs:
- job: Build_VS2019
  pool:
    vmImage: 'windows-2019'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '2.x' 
        addToPath: true 
    - script: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        where /R "%ProgramFiles(x86)%" dbghelp.dll
        where /R "%ProgramW6432%" dbghelp.dll
        python build-win.py
    - script: nuget push *.nupkg %NUGET_API_KEY% -Source https://nuget.org/
